apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deliverycenter-service-osrm-car
  name: deliverycenter-service-osrm-car
  namespace: staging
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: deliverycenter-service-osrm-car
  template:
    metadata:
      labels:
        app: deliverycenter-service-osrm-car
    spec:
      containers:
      - image: gcr.io/deliverycenter-stag/deliverycenter-service-osrm:latest
        name: deliverycenter-service-osrm-car
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "8Gi"
            cpu: "3"
          requests:
            memory: "7Gi"
            cpu: "2"
        readinessProbe:
          httpGet:
            path: /nearest/v1/healthz/0,0
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        stdin: true
        tty: true
status: {}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: deliverycenter-service-osrm-car-hpa
  namespace: staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deliverycenter-service-osrm-car
  maxReplicas: 4
  minReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 6Gi