apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deliverycenter-service-osrm-car
  name: deliverycenter-service-osrm-car
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliverycenter-service-osrm-car
  template:
    metadata:
      labels:
        app: deliverycenter-service-osrm-car
    spec:
      containers:
      - image: gcr.io/deliverycenter-stag/deliverycenter-service-osrm:car
        name: deliverycenter-service-osrm-car
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "12Gi"
            cpu: "3"
          requests:
            memory: "10Gi"
            cpu: "2"
        readinessProbe:
          httpGet:
            path: /nearest/v1/healthz/0,0
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        stdin: true
        tty: true
      nodeSelector:
        osrm: "true"
status: {}