apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deliverycenter-service-osrm-bicycle
  name: deliverycenter-service-osrm-bicycle
  namespace: production
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: deliverycenter-service-osrm-bicycle
  template:
    metadata:
      labels:
        app: deliverycenter-service-osrm-bicycle
    spec:
      containers:
      - image: gcr.io/deliverycenter-prod/deliverycenter-service-osrm:latest
        name: deliverycenter-service-osrm-bicycle
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "16Gi"
            cpu: "3"
          requests:
            memory: "14Gi"
            cpu: "2"
        readinessProbe:
          httpGet:
            path: /nearest/v1/healthz/0,0
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources: {}
        stdin: true
        tty: true
status: {}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: deliverycenter-service-osrm-bicycle-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deliverycenter-service-osrm-bicycle
  maxReplicas: 2
  minReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 12Gi